### PR TITLE
0.4.2

### LINKED ISSUE #25: createTempUser's callback should have three params
`createTempUser(newUser, callback( err, persistentUser, newTempUser)`

the function already checks for the user being in the persistent collection. if there is a user, then `newTempUser` will just be `null`, but this is ambiguous, as `newTempUser = null` if the user isn't found in the temporary collection.

`persistentUser` should be `null` if the user is NOT found in the persistent collection. makes sense to me :fried_shrimp:

### PR DESCRIPTION
**Pull request by SaintDako**
will close #25

### CODE REVIEW

**Comment by frankcash** [comment]
Tomorrow, I am :sleeping:

**Comment by frankcash** [comment]
okay I'll test your updates after my talk at Fossetcon!

**Comment by frankcash** [comment]
Started testing. The secondary server example didn't work. Will debug more
tonight.

**Comment by SaintDako** [comment]
what was the error?

**Comment by frankcash** [comment]
It wasn't throwing an error and I didn't have time to debug this weekend.
(Was helping family). I will debug it Monday (tomorrow) afternoon and
submit a fix.

**Comment by SaintDako** [comment]
oh ok, what was going wrong? I was using it with no issue... I think NEV
just hates you </3

Sunny days,
Dakota

**Comment by SaintDako** [comment]
@frankcash what's up bro, I miss u

**Comment by frankcash** [comment]
Sorry sorry, the promise wasn't throwing an error like I said.  It wasn't working at all.  I'll have time to debug it more this Monday and hopefully solve it!  (sorry things are busy around the holidays)

**Comment by SaintDako** [comment]
hi @frankcash lol whoops we kinda let this die

**Comment by frankcash** [comment]
>snoozed 3 months ago

yeah, oops.

**Comment by SaintDako** [comment]
I don't even remember what the problems were. how should we go about this?

**Comment by SaintDako** [comment]
@frankcash since this doesn't bump package.json, maybe I should merge this, then we'll test 0.4.3?

**Comment by frankcash** [comment]
sure, I can test things during this week since I have spring break

**Pull request merged**
